/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)security_log.h    generated by: makeheader    Thu Jun 22 14:19:32 2017
 *
 *		built from:	log.ifc
 */

#ifndef security_log_h
#define security_log_h


#ifndef security_dll_h
  #include "security/security_dll.h"
#endif
#ifndef log_common_h
  #include "log/log_common.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif



/*i \ingroup RTILogNumberBitmapClass 
 *  \brief Bitmap to specify STATIC DISCOVERY module in log message number.
 *
 *  @see RTI_LOG_MODULE_MASK
 */
#define MODULE_SECURITY  (0x130000)

/*e \ingroup RTI_SecurityLogModule
 * Submodule ID for plugin submodule
 */
#define SUBMODULE_SECURITY_COMMON         (0x1000)
#define SUBMODULE_SECURITY_AUTHENTICATION (0x2000)
#define SUBMODULE_SECURITY_ACCESS_CONTROL (0x4000)
#define SUBMODULE_SECURITY_CRYPTOGRAPHY   (0x8000)
#define SUBMODULE_SECURITY_LOGGING        (0x10000)


/*e \ingroup RTI_SecurityLogModule
 * Mask for turning on logging for only the plugin submodule
 */
#define RTI_SECURITY_SUBMODULE_MASK_COMMON                 (0x0001)
#define RTI_SECURITY_SUBMODULE_MASK_AUTHENTICATION         (0x0002)
#define RTI_SECURITY_SUBMODULE_MASK_ACCESS_CONTROL         (0x0004)
#define RTI_SECURITY_SUBMODULE_MASK_CRYPTOGRAPHY           (0x0008)
#define RTI_SECURITY_SUBMODULE_MASK_SECURITY               (0x0010)
#define RTI_SECURITY_SUBMODULE_MASK_LOGGING                (0x0020)

/*e \ingroup RTI_SecurityLogModule
 * Plugin class names for plugin logging
 */
#define RTI_SECURITY_COMMON_PLUGIN_CLASS \
    DDS_LOGGING_COMMON_CLASS

#define RTI_SECURITY_AUTHENTICATION_PLUGIN_CLASS \
    DDS_LOGGING_AUTHENTICATION_CLASS

#define RTI_SECURITY_ACCESS_CONTROL_PLUGIN_CLASS \
    DDS_LOGGING_ACCESS_CONTROL_CLASS

#define RTI_SECURITY_CRYPTOGRAPHY_PLUGIN_CLASS \
    DDS_LOGGING_CRYPTOGRAPHY_CLASS

#define RTI_SECURITY_SECURITY_PLUGIN_CLASS \
    DDS_LOGGING_SECURITY_CLASS

#define RTI_SECURITY_LOGGING_PLUGIN_CLASS \
     DDS_LOGGING_LOGGING_CLASS

/*e \ingroup RTI_SecurityLogModule
 * Mask for turning on logging for all submodules
 */
#define RTI_SECURITY_SUBMODULE_MASK_ALL              (0xFFFF)

extern RTISecurityDllExport
void RTI_Security_Log_setVerbosity(RTILogBitmap submoduleMask, int verbosity);

extern RTISecurityDllExport
void RTI_Security_Log_setBitmaps(
        RTILogBitmap submoduleMask,
        RTILogBitmap instrumentationMask);

extern RTISecurityDllExport
void RTI_Security_Log_getBitmaps(
        RTILogBitmap *submoduleMask,
        RTILogBitmap *instrumentationMask);


#ifdef __cplusplus
}    /* extern "C" */
#endif

#endif /* security_log_h */
