/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)log_dll.h    generated by: makeheader    Thu Jun 22 14:16:45 2017
 *
 *		built from:	dll.ifc
 */

#ifndef log_dll_h
#define log_dll_h



#if defined(RTI_WIN32) || defined(RTI_WINCE)
  #if defined(RTI_log_DLL_EXPORT)
    #define RTILogDllExport __declspec( dllexport )
  #else
    #define RTILogDllExport
  #endif /* RTI_log_DLL_EXPORT */

  #if defined(RTI_log_DLL_VARIABLE) 
    #if defined(RTI_log_DLL_EXPORT)
      #define RTILogDllVariable __declspec( dllexport )
    #else
      #define RTILogDllVariable __declspec( dllimport )
    #endif /* RTI_log_DLL_EXPORT */
  #else 
    #define RTILogDllVariable
  #endif /* RTI_log_DLL_VARIABLE */
#else
  #define RTILogDllExport
  #define RTILogDllVariable
#endif /* RTI_WIN32 || RTI_WINCE */


#endif /* log_dll_h */
