/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)ndds_version.h    generated by: makeheader    Thu Jun 22 14:17:49 2017
 *
 *		built from:	ndds_version.ifc
 */

#ifndef ndds_version_h
#define ndds_version_h


#define RTI_DDS_VERSION_MAJOR  5
#define RTI_DDS_VERSION_MINOR  3
#define RTI_DDS_VERSION_RELEASE 0
#define RTI_DDS_VERSION_REVISION 0

#endif /* ndds_version_h */
