/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)osapi_sharedMemorySegment.h    generated by: makeheader    Thu Jun 22 14:16:50 2017
 *
 *		built from:	sharedMemorySegment.ifc
 */

#ifndef osapi_sharedMemorySegment_h
#define osapi_sharedMemorySegment_h


  #ifndef osapi_sharedMemory_h
    #include "osapi/osapi_sharedMemory.h"
  #endif

#ifdef __cplusplus
    extern "C" {
#endif

struct RTIOsapiSharedMemorySegmentHandle;

extern RTIOsapiDllExport RTIBool
RTIOsapiSharedMemorySegment_create(
		struct RTIOsapiSharedMemorySegmentHandle *handle,
		int* statusOut,
		int key, 
		int size, 
		RTI_UINT64 pidIn);

extern RTIOsapiDllExport RTIBool
RTIOsapiSharedMemorySegment_attach(
		struct RTIOsapiSharedMemorySegmentHandle *handle,
		int* statusOut,
		int key);

extern RTIOsapiDllExport RTIBool
RTIOsapiSharedMemorySegment_createOrAttach(
		struct RTIOsapiSharedMemorySegmentHandle *handle,
		int* statusOut,
		int key, 
		int size, 
		RTI_UINT64 pidIn);

extern RTIOsapiDllExport
char *RTIOsapiSharedMemorySegment_getAddress(
		struct RTIOsapiSharedMemorySegmentHandle *handle);

extern RTIOsapiDllExport
int RTIOsapiSharedMemorySegment_getSize(
		struct RTIOsapiSharedMemorySegmentHandle *handle);

extern RTIOsapiDllExport
int RTIOsapiSharedMemorySegment_getKey(
		struct RTIOsapiSharedMemorySegmentHandle *handle);

extern RTIOsapiDllExport
RTIBool RTIOsapiSharedMemorySegment_detach(
		struct RTIOsapiSharedMemorySegmentHandle *handle);

extern RTIOsapiDllExport
RTIBool RTIOsapiSharedMemorySegment_delete(
		struct RTIOsapiSharedMemorySegmentHandle *handle);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

  #include "osapi/osapi_sharedMemorySegment_impl.h"

#endif /* osapi_sharedMemorySegment_h */
