/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_sequence.h    generated by: makeheader    Thu Jun 22 14:17:53 2017
 *
 *		built from:	sequence.ifcxx
 */

#ifndef dds_cpp_sequence_h
#define dds_cpp_sequence_h


  #ifndef dds_cpp_dll_h
    #include "dds_cpp/dds_cpp_dll.h"
  #endif
  #ifndef dds_c_sequence_h
    #include "dds_c/dds_c_sequence.h"
  #endif

#endif /* dds_cpp_sequence_h */
