/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataWriter.h    generated by: makeheader    Thu Jun 22 14:17:55 2017
 *
 *		built from:	TDataWriter.cxx
 */

#ifndef dds_cpp_data_TDataWriter_h
#define dds_cpp_data_TDataWriter_h

#endif /* dds_cpp_data_TDataWriter_h */
