/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)core_version_buildid.h    generated by: makeheader    Thu Jun 22 14:17:39 2017
 *
 *		built from:	buildid.ifc
 */

#ifndef core_version_buildid_h
#define core_version_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCORE_BUILD_5.3.0.0_20170622T204835Z_RTI_REL"
#endif

#endif /* core_version_buildid_h */
