/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_data_TTypeSupport.h    generated by: makeheader    Thu Jun 22 14:17:50 2017
 *
 *		built from:	TTypeSupport.c
 */

#ifndef dds_c_data_TTypeSupport_h
#define dds_c_data_TTypeSupport_h

#ifdef __cplusplus
    extern "C" {
#endif

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_data_TTypeSupport_h */
