/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)reda_epoch_impl.h    generated by: makeheader    Thu Jun 22 14:16:57 2017
 *
 *		built from:	epoch_impl.ifc
 */

#ifndef reda_epoch_impl_h
#define reda_epoch_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


  #define REDAEpoch_isGreater(me, value) \
    (((value) - (me)) >= REDA_EPOCH_HALF_VALUE)

  #define REDAEpoch_isLess(me, value) \
    (((me) - (value)) >= REDA_EPOCH_HALF_VALUE)


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* reda_epoch_impl_h */
