/* (c) Copyright 2003-2015, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_buildid.h    generated by: makeheader    Thu Jun 22 14:17:49 2017
 *
 *		built from:	buildid.ifc
 */

#ifndef dds_c_buildid_h
#define dds_c_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSC_BUILD_5.3.0.0_20170622T204835Z_RTI_REL"
#endif

#endif /* dds_c_buildid_h */
