RTI Connext .Net APIs: DDS::StringTypeSupport Class Reference
DDS::StringTypeSupport Class Reference
RTI Connext DDS API Reference » Topic Module » Built-in Types » String Built-in Type
<<interface>> String type support.
#include <managed_stringwrapperSupport.h>
Inherits DDS::TypedTypeSupport< T >.
Static Public Member Functions
static System::String ^ get_type_name ()
Get the default name for the System::String type.
static void print_data (System::String^ a_data)
<<extension>> Print value of data type to standard out.
static void register_type (DDS::DomainParticipant^ participant, System::String^ type_name)
Allows an application to communicate to RTI Connext the existence of the System::String data type.
static void unregister_type (DDS::DomainParticipant^ participant, System::String^ type_name)
Allows an application to unregister the System::String data type from RTI Connext. After calling unregister_type, no further communication using this type is possible.
static void serialize_data_to_cdr_buffer (array< System::Byte >^ buffer, System::UInt32% length, String^ a_data)
<<extension>> Serializes the input sample into a buffer of octets.
static String ^ deserialize_data_from_cdr_buffer (array< System::Byte >^ buffer, System::UInt32 length)
<<extension>> Deserializes a sample from a buffer of octets.
static System::String ^ data_to_string (String^ sample, PrintFormatProperty^ formatProperty)
<<extension>> Get the string representation of an input sample.
static System::String ^ data_to_string (String^ sample)
<<extension>> Get the string representation of an input sample.
static DDS::TypeCode ^ get_typecode ()
<<extension>> Retrieves the TypeCode for the Type.
Detailed Description
<<interface>> String type support.
Member Function Documentation
get_type_name()
static System::String ^ DDS::StringTypeSupport::get_type_name () static
Get the default name for the System::String type.
Can be used for calling DDS::StringTypeSupport::register_type or creating DDS::Topic.
Returns
default name for the System::String type.
See also
DDS::StringTypeSupport::register_type
DDS::DomainParticipant::create_topic
print_data()
static void DDS::StringTypeSupport::print_data (System::String^ a_data) inline static
<<extension>> Print value of data type to standard out.
The generated implementation of the operation knows how to print value of a data type.
Parameters
a_data <<in>> String to be printed.
register_type()
static void DDS::StringTypeSupport::register_type (DDS::DomainParticipant^ participant, System::String^ type_name) static
Allows an application to communicate to RTI Connext the existence of the System::String data type.
By default, The System::String built-in type is automatically registered when a DomainParticipant is created using the type_name returned by DDS::StringTypeSupport::get_type_name. Therefore, the usage of this function is optional and it is only required when the automatic built-in type registration is disabled using the participant property "dds.builtin_type.auto_register".
This method can also be used to register the same DDS::StringTypeSupport with a DDS::DomainParticipant using different values for the type_name.
If register_type is called multiple times with the same DDS::DomainParticipant and type_name, the second (and subsequent) registrations are ignored by the operation.
Parameters
participant <<in>> the DDS::DomainParticipant to register the data type System::String with. Cannot be null.
type_name <<in>> the type name under with the data type System::String is registered with the participant; this type name is used when creating a new DDS::Topic. (See DDS::DomainParticipant::create_topic.) The name may not be null or longer than 255 characters.
Exceptions
One of the Standard Return Codes, DDS::Retcode_PreconditionNotMet or DDS::Retcode_OutOfResources.
MT Safety:
UNSAFE on the FIRST call. It is not safe for two threads to simultaneously make the first call to register a type. Subsequent calls are thread safe.
See also
DDS::DomainParticipant::create_topic
Referenced by print_data().
unregister_type()
static void DDS::StringTypeSupport::unregister_type (DDS::DomainParticipant^ participant, System::String^ type_name) static
Allows an application to unregister the System::String data type from RTI Connext. After calling unregister_type, no further communication using this type is possible.
Precondition
The System::String type with type_name is registered with the participant and all DDS::Topic objects referencing the type have been destroyed. If the type is not registered with the participant, or if any DDS::Topic is associated with the type, the operation will fail with DDS::Retcode_Error.
Postcondition
All information about the type is removed from RTI Connext. No further communication using this type is possible.
Parameters
participant <<in>> the DDS::DomainParticipant to unregister the data type System::String from. Cannot be null.
type_name <<in>> the type name under with the data type System::String is registered with the participant. The name should match a name that has been previously used to register a type with the participant. Cannot be null.
Exceptions
One of the Standard Return Codes, DDS::Retcode_BadParameter or DDS::Retcode_Error
MT Safety:
SAFE.
See also
DDS::StringTypeSupport::register_type
Referenced by print_data().
serialize_data_to_cdr_buffer()
static void DDS::StringTypeSupport::serialize_data_to_cdr_buffer (array< System::Byte >^ buffer, System::UInt32% length, String^ a_data) static
<<extension>> Serializes the input sample into a buffer of octets.
See also
FooTypeSupport::serialize_data_to_cdr_buffer
Referenced by print_data().
deserialize_data_from_cdr_buffer()
static String ^ DDS::StringTypeSupport::deserialize_data_from_cdr_buffer (array< System::Byte >^ buffer, System::UInt32 length) static
<<extension>> Deserializes a sample from a buffer of octets.
See also
FooTypeSupport::deserialize_data_from_cdr_buffer
Referenced by print_data().
data_to_string() [1/2]
static System::String ^ DDS::StringTypeSupport::data_to_string (String^ sample, PrintFormatProperty^ formatProperty) static
<<extension>> Get the string representation of an input sample.
See also
FooTypeSupport::data_to_string
Referenced by print_data().
data_to_string() [2/2]
static System::String ^ DDS::StringTypeSupport::data_to_string (String^ sample) static
<<extension>> Get the string representation of an input sample.
Use the default values for DDS::PrintFormatProperty to create the output string.
See also
FooTypeSupport::data_to_string
get_typecode()
static DDS::TypeCode ^ DDS::StringTypeSupport::get_typecode () static
<<extension>> Retrieves the TypeCode for the Type.
See also
FooTypeSupport::get_typecode
Referenced by print_data().
RTI Connext .Net APIs Version 5.3.0 Copyright © Sun Jun 25 2017 Real-Time Innovations, Inc